Rework error handling
- Throw `DiceException` instead of `InvalidArgumentException`
- Improve upon `ArgumentCountError: Too few arguments to function` by
  removing `try`/`catch` in `getParams()` so `DiceException` is thrown